Update wolfenstein3dfromsource.yml
fix config.log part of failure-debugging

diff --git a/.github/workflows/wolfenstein3dfromsource.yml b/.github/workflows/wolfenstein3dfromsource.yml
--- a/.github/workflows/wolfenstein3dfromsource.yml
+++ b/.github/workflows/wolfenstein3dfromsource.yml
@@ -19,7 +19,11 @@ jobs:
       run: |
         if test -x "$(which locate)" && locate --version >/dev/null 2>/dev/null; then \
           echo "locating <GL/glu.h>..."; \
-          locate "GL/glu.h" || (echo "locating <GL/glu.h> failed!" && (test -r config.log && cat config.log)); \
+          locate "GL/glu.h" || echo "locating <GL/glu.h> failed!"; \
+          if test -r config.log; then cat config.log; \
+          elif test -r wolf3dredux_0.01/config.log; then \
+            stat wolf3dredux_0.01/config.log && cat wolf3dredux_0.01/config.log; \
+          fi; \
         elif test -x "$(which mlocate)"; then \
           echo "mlocate-ing <GL/glu.h>..."; \
           mlocate "GL/glu.h" || echo "mlocate-ing <GL/glu.h> failed!"; \
